# Generated by Django 2.2.8 on 2020-01-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='genre',
            field=models.CharField(blank=True, choices=[('adventure', 'Adventure'), ('wildlife', 'Wildlife'), ('lifestyle', 'Lifestyle'), ('technology', 'Technology'), ('music', 'Music')], max_length=50, null=True),
        ),
    ]
