# Generated by Django 3.0.2 on 2020-01-13 09:52

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title_image',
            field=models.ImageField(blank=True, null=True, upload_to=articles.models.upload_to),
        ),
    ]
