# Generated by Django 3.0.2 on 2020-01-16 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0003_article_title_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.CharField(blank=True, choices=[('one', '1 Star'), ('two', '2 Star'), ('three', '3 Star'), ('four', '4 Star'), ('five', '5 Star')], max_length=50, null=True, verbose_name='Stars')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Feedback')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='articles.Article', verbose_name='article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer')),
            ],
        ),
    ]
